steps:
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['init']
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['plan', '-out=plan']
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ["apply", "plan"]
artifacts:
  objects:
    location: 'gs://certificates-123/'
    paths: ['certificate.pem', 'private_key.pem']
