steps:
- name: 'certbot/dns-google'
  args: ["certonly",
    "--dns-google",
    "--email", "admin@cloudevops.it",
    "--agree-tos", 
    "-n",
    "--test-cert",
    "-d", "vault.cloudevops.it"
    ]
artifacts:
  objects:
    location: 'gs://certificates-123/'
    paths: ['/etc/letsencrypt/live/*']
