steps:
- name: 'certbot/dns-google'
  args: [
    "certonly",
    "--agree-tos", "-m", "admin@cloudevops.it",
    "--non-interactive",
    "--dns-google",
    "--dns-google-propagation-seconds", "90",
    "--domain", "vault.cloudevops.it",
    "--test-cert"
    ]
artifacts:
  objects:
    location: 'gs://certificates-123/'
    paths: ['/etc/letsencrypt/live/*']
